### PR TITLE
UI demo, Overlaying images/text 

### PR DESCRIPTION
**Pull request by staberas**

### CODE REVIEW

**Comment by Gitshaoxiang** [comment]
hi. thank your example PR.   could you change the .ino file name and the folder name to be the same?  this is the Arduino lib example rule.   else the example can't display in the Arduino IDE example list.....

**Review by Zontex — CHANGES_REQUESTED** [review]
Hi, when you push file make sure to save the file at the same name of the folder.
for example: here the folder name is Overlaying UI Elements but the file name is UI_Demo.ino. you need to change the file name to Overlaying UI Elements.ino else the arduino IDE cannot recognize the project file.

Please make those changes and we will approve :)

**Comment by staberas** [comment]
Fixed - renamed filename

**Review by Zontex — APPROVED** [review]
Thanks for changing the name! Approved.

**Pull request merged**
